format_version: 10
pipelines:
  convert_image:
    group: latam02
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-ec62e6d:
        git: https://github.com/latam02/converter_image.git
        username: ChristianTC
        shallow_clone: false
        auto_update: true
        branch: ct-jenkins
        encrypted_password: AES:xgnGplfgVKlxsLKvKWc7ng==:AVcoKefYW/cEUCF3Jkx04+29DNVMhmlHChuz3GizhIE=
    stages:
    - unitTest:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          unit:
            resources:
              - ubuntu
            timeout: 0
            tasks:
            - exec:
                arguments:
                - -c
                - pip install -r requirements.txt
                command: bash
                run_if: passed
